# Generated by Django 4.2.16 on 2024-11-25 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("info", "0003_itineraryitem"),
    ]

    operations = [
        migrations.AddField(
            model_name="itineraryitem",
            name="scheduled_on",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
